export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
export const UPDATE_CATEGORY_ID = 'UPDATE_CATEGORY_ID';
export const UPDATE_SUB_CATEGORY_ID = 'UPDATE_SUB_CATEGORY_ID';
export const UPDATE_PROJECT_IMAGE = 'UPDATE_PROJECT_IMAGE';
export const UPDATE_PROJECT_VIDEO_URL = 'UPDATE_PROJECT_VIDEO_URL';

export const UPDATE_LAUNCH_DATE = 'UPDATE_LAUNCH_DATE';
export const UPDATE_END_DATE = 'UPDATE_END_DATE';
export const UPDATE_GOAL = 'UPDATE_GOAL';
export const UPDATE_CHECKED = 'UPDATE_CHECKED';

export const UPDATE_EDITOR = 'UPDATE_EDITOR';
export const UPDATE_RISKS = 'UPDATE_RISKS';

export const SET_USER_COMPANIES = 'SET_USER_COMPANIES';
export const NEED_UPDATE_USER_COMPANIES = 'NEED_UPDATE_USER_COMPANIES';

export const LOAD_COMPANY = 'LOAD_COMPANY';